apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-argocd
      namespace: dotnet-argocd
  template:
    metadata:
      labels:
        app: dotnet-argocd
    spec:
      containers:
        - name: dotnet-argocd
          image: your-docker-image:latest
          ports:
            - containerPort: 80
