apiVersion: v1
kind: Service
metadata:
  name: dotnet-argocd
  namespace: dotnet-argocd
spec:
  selector:
    app: dotnet-argocd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
